-- Database and Schema Setup
CREATE DATABASE IF NOT EXISTS RETAIL_ANALYTICS;
USE DATABASE RETAIL_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS MONITORING;

-- Uncomment and adjust for your environment:
-- CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
--     WITH WAREHOUSE_SIZE = 'X-SMALL'
--     AUTO_SUSPEND = 60
--     AUTO_RESUME = TRUE
--     INITIALLY_SUSPENDED = TRUE;
